
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:14 (project)"
    message: |
      The target system is: iOS -  - 
      The host system is: Linux - 6.8.0-1044-azure - x86_64
...
